###############
## 
####

GPU: [0,1]

VERBOSE: True

MODEL:
  MODE: 'Deblurring'
  MODEL_NAME: 'IdemNetStage4'
  SESSION: 'IdemNetGRU'
  TIMES: 2

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 6
  NUM_EPOCHS: 3000
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 20
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: './Datasets/GoPro/train' # path to training data
  VAL_DIR: './Datasets/GoPro/test'    # path to validation data
  SAVE_BASE_DIR: 'experiments'    # path to save models and images
  LOG_NAME: 'LossForAllDetach_Retrain'
  # SAVE_IMAGES: False
